FEATURE: add catch and diary
HonKLam/fishdex pull request #17
Opened 2024-04-08 12:57 UTC by xChieko

## Welches Ticket löst du?

#15 WITHOUT optional feature (API Schnittstellen)

## Was hast du geändert?

Kurze Zusammenfassung der Änderungen:

Catch + Diary Funktionalitäten (genau so aufgebaut wie Fish und Fishdex)

## Hast du darüber mit dem Team gesprochen?

- [x] Ja, das Team ist informiert und einverstanden.

## Hast du deinen Code kommentiert (wo es nötig ist)?

- [ ] Ja, ich habe meinen Code kommentiert, wo nötig.

## Hast du deinen Code getestet?

- [x] Ja, ich habe die App über Docker gestartet und alles ausprobiert. Die Website verhält sich normal und es treten keine Fehlermeldungen auf.

## Alles weitere, was wichtig sein könnte:
--

2024-04-08 14:40 UTC, HonKLam commented
Ich würde vorschlagen, dass du Kommentare und API Schnittstelle noch in dem Branch hinzufügst (wenn API nicht too much ist) und wir dann mit nur 1 PR auch 1 Ticket fertigmachen

2024-04-08 16:12 UTC, xChieko commented
Klingt gut :) 
Kommis sind jetzt da,  API Schnittstelle probier ich jetzt mal :)

2024-04-08 16:15 UTC, xChieko commented
Sind die API-Schnittstellen noch nicht da, @HonKLam?

2024-04-09 12:32 UTC, HonKLam commented
hmmm das handlen von den einzelnen API-Schnittstellen Endpunkten wird etwas sehr unübersichtlich. Ich würde mal schauen, wie wir das handlen der Anfragen (also die Logik zum Bearbeiten der API-Anfragen) in extra Klassen (so ne Art "Service-Klasse") umverlegen können.

2024-04-16 08:46 UTC, HonKLam requested changes

2024-04-16 08:46 UTC, HonKLam commented on fd-backend/src/main/java/dev/hklm/fdbackend/Services/CatchService.java
> +    public void addCatch(Catch fishCatch) throws IOException {
Hier sollte
- die `fishId` aus dem Catch-Objekt gezogen werden 
- FishService verwenden um mit fishId den Counter im Fish-Objekt zu erhöhen (siehe unten)
- danach Catch in Diary hinzufügen
- Diary speichern

nutz für Counter den neuen `FishService` aus #22 
- [ ] erstell dort eine neue Methode `increaseFishCounter` der die fishId annimmt
- [ ] hole den Fish aus der Datenbank (mit der richtigen ID)
- [ ] erhöhe den Counter
- [ ] Speichere den Fisch wieder in der Datenbank

2024-04-16 09:50 UTC, HonKLam approved these changes
Sieht soweit gut aus, bitte nochmal testen tho ob alles auch so klappt

2024-04-16 09:50 UTC, HonKLam commented on fd-backend/src/main/java/dev/hklm/fdbackend/Entities/Catch.java
> +
War nur so vor mich hingeschrieben, ein Setter brauchen wir aktuell nicht glaube

2024-04-16 10:50 UTC, HonKLam requested changes
Eine Kleinigkeit noch, bitte hinzufügen und dann noma kurz testen obs klappt und dann approve ich!

2024-04-16 10:50 UTC, HonKLam commented on fd-backend/src/main/java/dev/hklm/fdbackend/Entities/Catch.java
> +    @Basic(fetch = FetchType.LAZY)
Bitte füg über dem catchImage noch das hier hinzu:
`@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)`

Damit werden die Binärdaten von catchImage nicht mehr angezeigt, wenn man `GET /diary`macht

2024-04-16 11:47 UTC, HonKLam approved these changes
LGTM!

2024-04-16 11:48 UTC, merged